apiVersion: v1
kind: Service
metadata:
  name: cloud-native-application
spec:
  type: ClusterIP
  selector:
    app: cloud-native-app
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30001
