apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eks-app
  template:
    metadata:
      labels:
        app: eks-app
    spec:
      containers:
      - name: eks-app
        image: 641944126006.dkr.ecr.ap-south-1.amazonaws.com/project-5-ecr:latest
        ports:
        - containerPort: 5000
